// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bms} from '../models';
import {config} from '../models';

export function ClearSolarmanSession():Promise<void>;

export function ConnectSolarman():Promise<string>;

export function ExportExcel(arg1:bms.Config):Promise<string>;

export function ExportPDF(arg1:bms.SystemSnapshot):Promise<string>;

export function GatewayReachable(arg1:bms.Config):Promise<boolean>;

export function GetConfig():Promise<bms.Config>;

export function GetRemoteConfig():Promise<config.Remote>;

export function OpenSolarmanLogin():Promise<void>;

export function ReadRemote(arg1:string,arg2:number):Promise<bms.SystemSnapshot>;

export function ReadSystem(arg1:bms.Config):Promise<bms.SystemSnapshot>;

export function SaveConfig(arg1:bms.Config):Promise<void>;

export function TestConnection(arg1:bms.Config):Promise<bms.Identity>;

export function TestRemote(arg1:string):Promise<void>;

export function ToggleMaximise():Promise<void>;
