// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bms} from '../models';
import {plant} from '../models';
import {datastore} from '../models';
import {config} from '../models';

export function ClearSolarmanSession():Promise<void>;

export function ConnectSolarman():Promise<string>;

export function EvaluateRunGate(arg1:bms.SystemSnapshot,arg2:number):Promise<bms.RunGate>;

export function ExportExcel(arg1:bms.Config):Promise<string>;

export function ExportLogs(arg1:string,arg2:number):Promise<string>;

export function ExportPDF(arg1:bms.SystemSnapshot):Promise<string>;

export function GatewayReachable(arg1:bms.Config):Promise<boolean>;

export function GetConfig():Promise<bms.Config>;

export function GetDevices():Promise<Array<plant.Device>>;

export function GetLogging():Promise<datastore.Status>;

export function GetPolling():Promise<config.Polling>;

export function GetRemoteConfig():Promise<config.Remote>;

export function IssueRun(arg1:bms.Config,arg2:number,arg3:boolean,arg4:boolean):Promise<bms.RunResult>;

export function OpenSolarmanLogin():Promise<void>;

export function ReadPlant():Promise<plant.Snapshot>;

export function ReadRemote(arg1:string,arg2:number):Promise<bms.SystemSnapshot>;

export function ReadSystem(arg1:bms.Config):Promise<bms.SystemSnapshot>;

export function ResetDevices():Promise<Array<plant.Device>>;

export function SaveConfig(arg1:bms.Config):Promise<void>;

export function SaveDevices(arg1:Array<plant.Device>):Promise<void>;

export function SetLogging(arg1:config.Logging):Promise<datastore.Status>;

export function SetPolling(arg1:config.Polling):Promise<config.Polling>;

export function TestConnection(arg1:bms.Config):Promise<bms.Identity>;

export function TestRemote(arg1:string):Promise<void>;

export function ToggleMaximise():Promise<void>;
