// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSolarmanSession() {
  return window['go']['main']['App']['ClearSolarmanSession']();
}

export function ConnectSolarman() {
  return window['go']['main']['App']['ConnectSolarman']();
}

export function EvaluateRunGate(arg1, arg2) {
  return window['go']['main']['App']['EvaluateRunGate'](arg1, arg2);
}

export function ExportExcel(arg1) {
  return window['go']['main']['App']['ExportExcel'](arg1);
}

export function ExportLogs(arg1, arg2) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2);
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function GatewayReachable(arg1) {
  return window['go']['main']['App']['GatewayReachable'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetLogging() {
  return window['go']['main']['App']['GetLogging']();
}

export function GetPolling() {
  return window['go']['main']['App']['GetPolling']();
}

export function GetRemoteConfig() {
  return window['go']['main']['App']['GetRemoteConfig']();
}

export function IssueRun(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IssueRun'](arg1, arg2, arg3, arg4);
}

export function OpenSolarmanLogin() {
  return window['go']['main']['App']['OpenSolarmanLogin']();
}

export function ReadPlant() {
  return window['go']['main']['App']['ReadPlant']();
}

export function ReadRemote(arg1, arg2) {
  return window['go']['main']['App']['ReadRemote'](arg1, arg2);
}

export function ReadSystem(arg1) {
  return window['go']['main']['App']['ReadSystem'](arg1);
}

export function ResetDevices() {
  return window['go']['main']['App']['ResetDevices']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDevices(arg1) {
  return window['go']['main']['App']['SaveDevices'](arg1);
}

export function SetLogging(arg1) {
  return window['go']['main']['App']['SetLogging'](arg1);
}

export function SetPolling(arg1) {
  return window['go']['main']['App']['SetPolling'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestRemote(arg1) {
  return window['go']['main']['App']['TestRemote'](arg1);
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}
